

CREATE TABLE CHATROOM (
	CHATROOM_ID       INTEGER      NOT NULL AUTO_INCREMENT, -- CHATROOM_ID
	CHATROOM_MSG      VARCHAR(128) NOT NULL, -- CHATROOM_MSG
	CHATROOM_TIME     DATETIME         NOT NULL, -- CHATROOM_TIME
	CHATROOM_NICKNAME VARCHAR(45)  NOT NULL, -- CHATROOM_NICKNAME
	CHATLIST_ID       INTEGER      NOT NULL,  -- CHATLIST_ID
	PRIMARY KEY(CHATROOM_ID)
);

-- CHATROOM 기본키2
CREATE UNIQUE INDEX PK_CHATROOM
	ON CHATROOM ( -- CHATROOM
		CHATROOM_ID ASC -- CHATROOM_ID
	);

-- CHATROOM
ALTER TABLE CHATROOM
	ADD
		CONSTRAINT PK_CHATROOM -- CHATROOM 기본키2
		PRIMARY KEY (
			CHATROOM_ID -- CHATROOM_ID
		);

-- CHATROOM
ALTER TABLE CHATROOM
	ADD
		CONSTRAINT FK_CHATLIST_TO_CHATROOM -- CHATLIST -> CHATROOM
		FOREIGN KEY (
			CHATLIST_ID -- CHATLIST_ID
		)
		REFERENCES CHATLIST ( -- CHATLIST
			CHATLIST_ID -- CHATLIST_ID
		)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;