CREATE TABLE SOMEPLACE (
	SOMEPLACE_ID           INTEGER      NOT NULL AUTO_INCREMENT, -- SOMEPLACE_ID
	SOMEPLACE_TITLE        VARCHAR(64)  NOT NULL, -- SOMEPLACE_TITLE
	SOMEPLACE_TITLE_DETAIL VARCHAR(255) NOT NULL, -- SOMEPLACE_TITLE_DETAIL
	SOMEPLACE_DETAIL       VARCHAR(255) NOT NULL, -- SOMEPLACE_DETAIL
	SOMEPLACE_PHOTO        VARCHAR(128) NOT NULL, -- SOMEPLACE_PHOTO
	SOMEPLACE_PHOTO_CNT    INTEGER      NOT NULL,  -- SOMEPLACE_PHOTO_CNT
	PRIMARY KEY(SOMEPLACE_ID)
);

-- SOMEPLACE 기본키2
CREATE UNIQUE INDEX PK_SOMEPLACE
	ON SOMEPLACE ( -- SOMEPLACE
		SOMEPLACE_ID ASC -- SOMEPLACE_ID
	);

-- SOMEPLACE
ALTER TABLE SOMEPLACE
	ADD
		CONSTRAINT PK_SOMEPLACE -- SOMEPLACE 기본키2
		PRIMARY KEY (
			SOMEPLACE_ID -- SOMEPLACE_ID
		);