
-- STATEDETAIL
CREATE TABLE STATEDETAIL (
	STATEDETAIL_ID      INTEGER     NOT NULL AUTO_INCREMENT, -- STATEDETAIL_ID
	STATEDETAIL_LAT     DOUBLE      NOT NULL, -- STATEDETAIL_LAT
	STATEDETAIL_LNG     DOUBLE      NOT NULL, -- STATEDETAIL_LNG
	STATEDETAIL_CONTENT VARCHAR(45) NOT NULL, -- STATEDETAIL_CONTENT
	STATE_ID            INTEGER     NOT NULL,      -- STATE_ID
	PRIMARY KEY(STATEDETAIL_ID)
);

-- STATEDETAIL 기본키2
CREATE UNIQUE INDEX PK_STATEDETAIL
	ON STATEDETAIL ( -- STATEDETAIL
		STATEDETAIL_ID ASC -- STATEDETAIL_ID
	);

-- STATEDETAIL
ALTER TABLE STATEDETAIL
	ADD
		CONSTRAINT PK_STATEDETAIL -- STATEDETAIL 기본키2
		PRIMARY KEY (
			STATEDETAIL_ID -- STATEDETAIL_ID
		);

-- STATEDETAIL
ALTER TABLE STATEDETAIL
	ADD
		CONSTRAINT FK_STATE_TO_STATEDETAIL -- STATE -> STATEDETAIL
		FOREIGN KEY (
			STATE_ID -- STATE_ID
		)
		REFERENCES STATE ( -- STATE
			STATE_ID -- STATE_ID
		)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION; 

