
-- LIST
CREATE TABLE LIST (
	LIST_ID            INTEGER      NOT NULL AUTO_INCREMENT, -- LIST_ID
	LIST_DISTANCE      INTEGER      NOT NULL, -- LIST_DISTANCE
	LIST_PHOTO_ID      VARCHAR(128) NOT NULL, -- LIST_PHOTO_ID
	LIST_TIME          DATETIME         NOT NULL, -- LIST_TIME
	LIST_REMAIN_TIME   DATETIME         NOT NULL, -- LIST_REMAIN_TIME
	LIST_NUMBER_PEOPLE INTEGER      NOT NULL, -- LIST_NUMBER_PEOPLE
	LIST_LAT           DOUBLE       NOT NULL, -- LIST_LAT
	LIST_LNG           DOUBLE       NOT NULL, -- LIST_LNG
	LIST_OPEN_TIME     DATETIME         NOT NULL, -- LIST_OPEN_TIME
	LIST_PIN_CNT       INTEGER      NULL,     -- LIST_PIN_CNT
	LIST_GENDER        INTEGER      NOT NULL, -- LIST_GENDER
	USER_NICKNAME      VARCHAR(45)  NOT NULL,      -- USER_NICKNAME
	PRIMARY KEY(LIST_ID)
);

-- LIST 기본키
CREATE UNIQUE INDEX PK_LIST
	ON LIST ( -- LIST
		LIST_ID ASC -- LIST_ID
	);

-- LIST
ALTER TABLE LIST
	ADD
		CONSTRAINT PK_LIST -- LIST 기본키
		PRIMARY KEY (
			LIST_ID -- LIST_ID
		);

-- LIST
ALTER TABLE LIST
	ADD
		CONSTRAINT FK_USER_TO_LIST -- USER -> LIST
		FOREIGN KEY (
			USER_NICKNAME -- USER_NICKNAME
		)
		REFERENCES USER ( -- USER
			USER_NICKNAME -- USER_NICKNAME
		)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;
