
-- REPORT
CREATE TABLE REPORT (
	LIST_ID       INTEGER      NOT NULL AUTO_INCREMENT, -- LIST_ID
	REPORT_REASON VARCHAR(255) NOT NULL, -- REPORT_REASON
	REPORT_CNT    INTEGER      NOT NULL,  -- REPORT_CNT
	PRIMARY KEY(LIST_ID)
);

-- REPORT 기본키2
CREATE UNIQUE INDEX PK_REPORT
	ON REPORT ( -- REPORT
		LIST_ID ASC -- LIST_ID
	);

-- REPORT
ALTER TABLE REPORT
	ADD
		CONSTRAINT PK_REPORT -- REPORT 기본키2
		PRIMARY KEY (
			LIST_ID -- LIST_ID
		);

-- REPORT
ALTER TABLE REPORT
	ADD
		CONSTRAINT FK_LIST_TO_REPORT -- LIST -> REPORT
		FOREIGN KEY (
			LIST_ID -- LIST_ID
		)
		REFERENCES LIST ( -- LIST
			LIST_ID -- LIST_ID
		)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;