CREATE TABLE VERSION (
	VERSION_ID        VARCHAR(6) NOT NULL, -- VERSION_ID autoincrement는 int형만
	VERSION_ESSENTIAL INTEGER  Default '0' NOT NULL,  -- VERSION_ESSENTIAL
	PRIMARY KEY(VERSION_ID)
);

-- VERSION 기본키2
CREATE UNIQUE INDEX PK_VERSION
	ON VERSION ( -- VERSION
		VERSION_ID ASC -- VERSION_ID
	);

-- VERSION
ALTER TABLE VERSION
	ADD
		CONSTRAINT PK_VERSION -- VERSION 기본키2
		PRIMARY KEY (
			VERSION_ID -- VERSION_ID
		);
