
-- PIN
CREATE TABLE PIN (
	PIN_ID           INTEGER     NOT NULL AUTO_INCREMENT, -- PIN_ID
	PIN_TIME         DATETIME    DEFAULT CURRENT_TIMESTAMP NOT NULL, -- PIN_TIME
	PIN_FROM_USER_ID VARCHAR(45) NOT NULL, -- PIN_FROM_USER_ID
	PIN_TO_USER_ID   VARCHAR(45) NOT NULL, -- PIN_TO_USER_ID
	LIST_ID          INTEGER     NOT NULL,  -- LIST_ID
	PRIMARY KEY(PIN_ID)
);

-- PIN 기본키
CREATE UNIQUE INDEX PK_PIN
	ON PIN ( -- PIN
		PIN_ID ASC -- PIN_ID
	);

-- PIN
ALTER TABLE PIN
	ADD
		CONSTRAINT PK_PIN -- PIN 기본키
		PRIMARY KEY (
			PIN_ID -- PIN_ID
		);

-- PIN
ALTER TABLE PIN
	ADD
		CONSTRAINT FK_LIST_TO_PIN -- LIST -> PIN
		FOREIGN KEY (
			LIST_ID -- LIST_ID
		)
		REFERENCES LIST ( -- LIST
			LIST_ID -- LIST_ID
		)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;