

CREATE TABLE CHATLIST (
	CHATLIST_ID           INTEGER      NOT NULL AUTO_INCREMENT, -- CHATLIST_ID
	CHATLIST_MESSAGE      VARCHAR(128) NULL,     -- CHATLIST_MESSAGE
	CHATLIST_TIME         DATETIME         NOT NULL, -- CHATLIST_TIME
	CHATLIST_CONNECT      INTEGER      DEFAULT '0' NOT NULL, -- CHATLIST_CONNECT
	CHATLIST_LAST_MSG     VARCHAR(128) NULL,     -- CHATLIST_LAST_MSG
	CHATLIST_DEL          INTEGER      DEFAULT '0' NOT NULL, -- CHATLIST_DEL
	CHATLIST_FROM_USER_ID VARCHAR(45)  NOT NULL, -- CHATLIST_FROM_USER_ID
	CHATLIST_TO_USER_ID   VARCHAR(45)  NOT NULL, -- CHATLIST_TO_USER_ID
	PIN_ID                INTEGER      NOT NULL,      -- PIN_ID
	PRIMARY KEY(CHATLIST_ID)
);

-- CHATLIST 기본키2
CREATE UNIQUE INDEX PK_CHATLIST
	ON CHATLIST ( -- CHATLIST
		CHATLIST_ID ASC -- CHATLIST_ID
	);

-- CHATLIST
ALTER TABLE CHATLIST
	ADD
		CONSTRAINT PK_CHATLIST -- CHATLIST 기본키2
		PRIMARY KEY (
			CHATLIST_ID -- CHATLIST_ID
		);

-- CHATLIST
ALTER TABLE CHATLIST
	ADD
		CONSTRAINT FK_PIN_TO_CHATLIST -- PIN -> CHATLIST
		FOREIGN KEY (
			PIN_ID -- PIN_ID
		)
		REFERENCES PIN ( -- PIN
			PIN_ID -- PIN_ID
		)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

