
-- NOTI
CREATE TABLE NOTI (
	NOTI_ID              INTEGER      NOT NULL AUTO_INCREMENT, -- NOTI_ID
	NOTI_CONTENT         VARCHAR(255) NOT NULL, -- NOTI_CONTENT
	NOTI_ISREAD          INTEGER      NOT NULL DEFAULT 0, -- NOTI_ISREAD
	NOTI_INSERT_DATETIME DATETIME     DEFAULT NOW() NOT NULL,     -- NOTI_INSERT_DATETIME
	NOTI_THUMB           VARCHAR(128) NOT NULL,  -- NOTI_THUMB
	PRIMARY KEY(NOTI_ID)
);

-- NOTI 기본키
CREATE UNIQUE INDEX PK_NOTI
	ON NOTI ( -- NOTI
		NOTI_ID ASC -- NOTI_ID
	);

-- NOTI
ALTER TABLE NOTI
	ADD
		CONSTRAINT PK_NOTI -- NOTI 기본키
		PRIMARY KEY (
			NOTI_ID -- NOTI_ID
		);
