

-- USER
CREATE TABLE USER (
	USER_ID           INTEGER      NOT NULL AUTO_INCREMENT, -- USER_ID
	USER_NICKNAME     VARCHAR(45)  NOT NULL, -- USER_NICKNAME
	USER_NAME         VARCHAR(45)  NOT NULL, -- USER_NAME
	USER_PASSWORD     VARCHAR(128) NOT NULL, -- USER_PASSWORD
	USER_PHONE        VARCHAR(20)  NOT NULL, -- USER_PHONE
	USER_FACEBOOK     VARCHAR(128) NULL,     -- USER_FACEBOOK
	USER_KAKAO        VARCHAR(128) NULL,     -- USER_KAKAO
	USER_PROFIL_PHOTO VARCHAR(128) NULL,     -- USER_PROFIL_PHOTO
	USER_COVER_PHOTO  VARCHAR(128) NULL,     -- USER_COVER_PHOTO
	USER_AGE          INTEGER      NOT NULL, -- USER_AGE
	USER_GENDER       INTEGER      NOT NULL, -- USER_GENDER
	USER_HEART_CNT    INTEGER      NOT NULL DEFAULT 5, -- USER_HEART_CNT
	COUPON_ID         INTEGER      NULL ,     -- COUPON_ID
	PRIMARY KEY(USER_ID)
);

-- USER 기본키
CREATE UNIQUE INDEX PK_USER
	ON USER ( -- USER
		USER_NICKNAME ASC -- USER_NICKNAME
	);

-- USER
ALTER TABLE USER
	ADD
		CONSTRAINT PK_USER -- USER 기본키
		PRIMARY KEY (
			USER_NICKNAME -- USER_NICKNAME
		);

-- USER
ALTER TABLE USER
	ADD
		CONSTRAINT FK_COUPON_TO_USER -- COUPON -> USER
		FOREIGN KEY (
			COUPON_ID -- COUPON_ID
		)
		REFERENCES COUPON ( -- COUPON
			COUPON_ID -- COUPON_ID
		)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION;

